In [7]:
import tensorflow as tf

In [8]:
print(tf.__version__)

1.3.0


In [9]:
hello = tf.constant("hello")
world = tf.constant("world")

In [10]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [11]:
result

b'helloworld'

In [12]:
a = tf.constant(10)
b = tf.constant(20)

In [13]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

30

In [16]:
fill_mat = tf.fill((4,4),10)

In [24]:
myzero = tf.zeros((4,4))

In [18]:
my_rand = tf.random_normal((4,4),mean=0,stddev=1.0)

In [19]:
my_rand_u = tf.random_uniform((4,4),minval=0,maxval=1)

In [25]:
my_ops = [fill_mat,myzero,my_rand,my_rand_u]

In [21]:
sess = tf.InteractiveSession()

In [26]:
for op in my_ops:
    print(sess.run(op))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ -1.40272069e+00   2.20370173e+00   2.31998539e+00  -1.58873582e+00]
 [  9.03473914e-01   4.81715240e-02  -4.94552314e-01  -1.05096209e+00]
 [  1.17839170e+00  -1.08693933e+00  -8.37445855e-01   1.30660343e-03]
 [ -1.92933345e+00   1.11552811e+00   6.06853366e-01  -5.22806160e-02]]
[[ 0.1811403   0.21937847  0.01461518  0.55109954]
 [ 0.68910134  0.84288502  0.07091677  0.92981279]
 [ 0.82949746  0.96200025  0.47583902  0.92685378]
 [ 0.26407051  0.98422778  0.73269141  0.06590164]]


In [27]:
a = tf.random_normal((5,5),mean=0,stddev=2)
b = tf.random_normal((5,5),mean=0,stddev=2)
c = tf.matmul(a,b)

In [28]:
print(sess.run(c))

[[  3.63130999   4.34463072  -3.6539526   -0.41933191  -3.72475767]
 [ -4.59877968   1.1669327  -18.68745804   4.66532516   9.17015076]
 [ -0.30982304 -10.90082836  -8.40855312  -5.77000332  10.28268147]
 [  2.54707766   5.48660898  -4.78611565   3.84973478  -4.8948679 ]
 [  9.33866405   8.57285404  -2.8837924    1.0019536  -15.00235081]]
